#ifndef _SOFTMIRROR_GLOBALS_H_
#define _SOFTMIRROR_GLOBALS_H_

// #define USE_SERIAL

#define CLIP(X, MIN, MAX) (X < MIN) ? MIN : ((X > MAX) ? MAX : X)
#define SCALE(X, MINI, MAXI, MINO, MAXO) ((X - MINI) / (MAXI - MINI)) * (MAXO - MINO) + MINO

#define NODE_LED 16
#define ESP_LED 2

#define PWM_BOARDS 2
#define OUTPUTS_PER_PWM_BOARD 3
#define MAX_NUMBER_OF_COILS PWM_BOARDS * OUTPUTS_PER_PWM_BOARD

#define MAX_NUMBER_OF_CLOSEST_COILS 6
#define COILMAP_SCALE_X 1
#define COILMAP_SCALE_Y 1

#define MAX_OSC_ADDRESS_LENGTH 32
#define MAX_OSC_STRING_ARG_LENGTH 32

#define MAX_TOTAL_SOCKET_MSG_LENGTH MAX_NUMBER_OF_COILS * 3 + 10
#define MAX_TOTAL_SOCKET_STRING_SIZE MAX_TOTAL_SOCKET_MSG_LENGTH * 10

#define MAX_CENTROID_MSG_PERIOD 500
#define CENTROID_DIST_THRESH 0.3f
#define CENTROID_SPEED_LO_THRESH 0.25f
#define CENTROID_SPEED_HI_THRESH 0.9f
#define CENTROID_SPEED_SMOOTH_FACTOR 0.25f

#define MAIN_PERIOD 5
#define PWM_CONTROL_MSG_PERIOD 200 // interpolation happens between messages
#define PWM_CURVE_SENSITIVITY_FACTOR 4.0f // GIVE MORE ROOM TO LOWEST VALUES
#define MIN_PWM_VALUE 0
#define MAX_PWM_VALUE 4095
#define INVERT_PWM false

enum ControlMode {
  ControlModeGesture = 0,
  ControlModeAutomatic
};

#endif /* _SOFTMIRROR_GLOBALS_H_ */

