#ifndef _SOFTMIRROR_SERVER_GLOBALCONFIG_H_
#define _SOFTMIRROR_SERVER_GLOBALCONFIG_H_

// #define USE_SERIAL

#define CLIP(X, MIN, MAX) (X < MIN) ? MIN : ((X > MAX) ? MAX : X)
#define SCALE(X, MINI, MAXI, MINO, MAXO) ((X - MINI) / (MAXI - MINI)) * (MAXO - MINO) + MINO

#define NODE_LED 16
#define ESP_LED 2

#define MAX_NUMBER_OF_COILS 64
#define MAX_NB_CLOSEST_COILS 3
#define COILMAP_SCALE_X 1
#define COILMAP_SCALE_Y 1

#define MAX_CLIENT_BOARDS 9

#define MAX_OSC_ADDRESS_LENGTH 32
#define MAX_OSC_STRING_ARG_LENGTH 32

// #define MAX_SOCKET_LINE_STRING_SIZE 32
#define MAX_TOTAL_SOCKET_MSG_LENGTH (MAX_NUMBER_OF_COILS * 3 + 10)
#define MAX_TOTAL_SOCKET_STRING_SIZE (MAX_TOTAL_SOCKET_MSG_LENGTH * 10)
#define MAX_SOCKET_COILFRAME_SIZE 

#define MAX_CENTROID_MSG_PERIOD 500
#define CENTROID_DIST_THRESH 0.25f
#define CENTROID_SPEED_LO_THRESH 0.2f
#define CENTROID_SPEED_HI_THRESH 0.9f
#define CENTROID_SPEED_SMOOTH_FACTOR 0.7f

#define MAIN_PERIOD 5
#define PWM_CONTROL_MSG_PERIOD 100 // interpolation happens between messages

#define MIN_PWM_VALUE 0
#define MAX_PWM_VALUE 1023
#define PWM_OUTPUTS_PER_NODEMCU 3

static const int PWM_PINS_ARRAY[] = { 5, 4, 0, 2, 14, 12, 13, 15, 3, 1 };

#endif /* _SOFTMIRROR_SERVER_GLOBALCONFIG_H_ */

